# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f72cd390226ec1e2a73bb3025fba0eb4dd58e24d5161a36ae9275e81f59db18a14d77c6a03bc9d027a1108e1506751808040b86405f4c9c7e112fa9704cdcae

test:
  secret_key_base: 2b67a538409be46f6a872f728600305204f574b34cbcda73c90c1ee64da25b915769423d77af3024101724fc6d4042ef01e472bb53e78b1dfb3618e58e8d5f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
